README.md

Switched to an absolute link for the unstructured image, so that it shows up correctly on the PyPI project page.
Make sure the image shows up on the github page for this branch.

chore: Make img link absolute

---

CHANGELOG.md
Makefile
docker/Dockerfile
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt
scripts/dl-models.sh
scripts/docker-build.sh
setup.py
test_unstructured_inference/models/test_model.py
test_unstructured_inference/test_api.py
unstructured_inference/__init__.py
unstructured_inference/__version__.py
unstructured_inference/models/__init__.py

Added code to download `oer-checkbox` model from a public [repo](https://huggingface.co/unstructuredio/oer-checkbox/) on huggingface. This should remove all dependencies on assets in private spaces and open the door for full use of this repo as a package.
Tested by building the container and deploying to a test EC2 instance.
```python
from unstructured_inference.models import get_model
get_model("checkbox")
```
Should show 2 downloading bars the first time you run this code, for the model binary and the model config.
Subsequent runs do not download anything (as long as the file is still present locally).

chore: store models on hf

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/logger.py
unstructured_inference/models/detectron2.py
unstructured_inference/models/tesseract.py

Clean up loggers for `unstructured-inference` so it doesn't have BasicConfig, a logger named  `unstructured_inference` will be added to the [logger config file](https://github.com/Unstructured-IO/unstructured-infra-tools/blob/main/logger_config.yaml) in `unstructured-infra-tools`.
Related PR: https://github.com/Unstructured-IO/unstructured/pull/106

chore: logger should not be setting up a BasicConfig

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_model.py
unstructured_inference/__version__.py
unstructured_inference/api.py
unstructured_inference/inference/layout.py
unstructured_inference/models/__init__.py

Small factorization, primarily moving some of the api processing code out to where it can be reused.
Functionality should be unchanged from a user perspective.
Tests should pass.
Curl should work while app is running locally:
- Run `make run-app-dev`
- Run the following curls from the `pipeline-oer/sample-docs` directory, or replace `fake-oer.pdf` with the path to another pdf:
```shell
curl -X 'POST' \
'localhost:8000/layout/pdf' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'file=@fake-oer.pdf' | jq -C . | less -R
```
Should succeed and return narrative sections.
```shell
curl -X 'POST' \
'localhost:8000/layout/pdf' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'model=checkbox' \
-F 'file=@fake-oer.pdf' | jq -C . | less -R …
```

feat: Refactor for local inference

---

CHANGELOG.md
README.md
setup.py
unstructured_inference/__version__.py

Having a non-pip dependency prevents `unstructured-inference` from being installed as a package from pypi, so this PR removes detectron2 from the `setup.py` dependencies. Also removed the code to fail the install if `torch` isn't installed - `torch` will be installed with `layoutparser`, and will be present when the user builds Detectron2 from source.
Instructions have been updated to reflect the changes.

chore: remove detectron from setup.py

---

CHANGELOG.md
test_unstructured_inference/test_api.py
unstructured_inference/__version__.py
unstructured_inference/api.py
unstructured_inference/inference/layout.py

Prepping release I realized some changes I thought I'd made never got in.
- Added `is_image` flag for `process_data_with_model` and `process_file_with_model`
- Added support for the above in the API
- Added testing for all of the above
Run from python terminal:
```python
from unstructured_inference.inference.layout import process_file_with_model
res = process_file_with_model('sample-docs/loremipsum.png', is_image=True)
res.pages[0].elements
print(res)
```
The output should show that several `Text` elements were found.
Run `make run-app-dev` and from a separate terminal make the following request:
```bash
curl -X 'POST' \
'http://localhost:8000/layout/image' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'file=@sample-docs/loremipsum.png' | jq -C . | less -R …
```

chore: cut release for image processing

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

When trying to open an image in the `from_image_file` method, trying to open an empty filename would produce some non-helpful error, when ideally it should raise `FileNotFoundError`. This PR ensures that a `FileNotFoundError` is raised.
With `main` branch active, run:
```python
DocumentLayout.from_image_file("")
```
Observe that you get an `AttributeError`. Run the code again from this branch, observe that you get a `FileNotFoundError`.

chore: raise file not found for images

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_detectron2.py
test_unstructured_inference/models/test_model.py
test_unstructured_inference/test_api.py
test_unstructured_inference/test_utils.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/models/base.py
unstructured_inference/models/detectron2.py
unstructured_inference/models/unstructuredmodel.py
unstructured_inference/utils.py

Refactor of model code to make it less dependent on detectron2. 
Creates an abstract model class `UnstructuredModel`, with inference triggered by calling the object. The class must be subclassed for each individual model type to at least guide the inference input to the right method (e.g. the `detect` method for detectron 2 models).
Detectron specific code has been moved to `unstructured_inference.models.detectron2`.
The code still uses layoutparser objects for convenience in the `layout` code preparing the input, and the output is assumed to be a layoutparser `Layout` object. We may not want output in this format for other model types, but it seems like a viable choice for an output format, so we might consider wrangling the format to this class.
Tests should be passing and the high …

refactor: generic model

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Somehow a duplicate `load_pdf` line got in, maybe during a merge. Removed one of them.
Thanks to [hyperknot](https://github.com/hyperknot) for pointing this out in [this issue](https://github.com/Unstructured-IO/unstructured-inference/issues/51).

fix: remove duplicate load pdf

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

From [issue 51](https://github.com/Unstructured-IO/unstructured-inference/issues/51) we have a report of `load_pdf` coming back with a non-empty list of layouts and an empty list of images. The reported fix was to install poppler.
I haven't been able to reproduce yet (if I try `from_file` without poppler installed I get a `RuntimeError` with a suggestion to install poppler), but it doesn't hurt to guard against a length mismatch, as that shouldn't happen and would cause subsequent code to fail. I added an error message that points the user at a possible poppler install issue.
I added a test that checks the error raises properly, so just look over the code and make sure it makes sense.

fix: catch len mismatch

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/models/yolox.py

The multithreading problem doesn't appears to happen on M1 chip (as it does in x64 processors)
This PR just removes Pool from DocumentLayout.get_elements_from_layout.

fix: removes multithreading for OCR

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Tesseract is putting some control characters in out_text, this PR just delete all of them

fix: removing control characters

---

CHANGELOG.md
scripts/version-sync.sh
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Stopgap fix for a bug that causes the parsing procedure to ignore pdf elements that are not contained within the bounds of an inferred/specified layout element.
With the following linked file, [loremipsum-flat.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/10927802/loremipsum-flat.pdf), try the code:
```python
doc = DocumentLayout.from_file('loremipsum-flat.pdf')
print(' '.join([el.text for el in doc.pages[0].elements]))
```
Observe that the output is blank on the main branch, but contains text on this branch.

fix: ocr when no elements are found in block

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Removes progress bar output while processing pdfs and image elements.

chore: remove tqdm output

---

CHANGELOG.md
requirements/base.txt
requirements/dev.txt
setup.py
unstructured_inference/__version__.py
unstructured_inference/models/paddle_ocr.py

Made `paddleocr` optional again, to avoid issues with `unstructured` docker image until we can resolve how to properly install `paddleocr` in Centos7.

fix: make paddleocr install optional

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Allows `extract_tables` parameter to be passed from higher level functions `process_file_with_model` and `process_data_with_model`.
Run:
```python
from unstructured_inference.inference.layout import process_file_with_model
process_file_with_model("sample-docs/loremipsum.pdf", model_name="yolox", extract_tables=False)
```
Should generate no errors.

feat: extend extract tables through interface

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layout.py

Fixed bug where wrong location keys were being used to vertically locate image objects, causing the images' vertical coordinates to be given in terms of distance from the bottom of the document while text elements had vertical coordinates in terms of distance from the top of the document.
Added test that fails before change, passes after change.
Ensure test `test_load_pdf_image_placement` fails on `main` branch, passes CI.

fix: image location

---

README.md

This PR corrects some errors in README, replaces the old API endpoints:
`/layout_v1/[pdf|image] `
with:
`/layout/[default|yolox]/[pdf|image]`
In order to test, just run the examples in the README.md, should work now

Corrected endpoints in README

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/detectron2.py
unstructured_inference/models/yolox.py

Added the capability to partition granular-scale elements that have been identified (words, characters) by proximity using the word/character height as a reference. In many cases this does a good job of grouping text blocks. Also moved logic for extracting text from a region into the region itself, so in the future different logic can be used for embedded text and images.
In a jupyter notebook, try the following code:
```python
from unstructured_inference.inference.layout import load_pdf
from unstructured_inference.inference.elements import partition_groups_from_regions
words, images = load_pdf('sample-docs/layout-parser-paper.pdf')
colors = ["red", "green", "blue", "cyan", "yellow", "magenta", "purple"] * 8
from PIL.ImageDraw import ImageDraw
def annotate_regions(rects, image, color): …
```

refactor: partition in elements

---

.github/workflows/create_issue.yml

Copied the workflow to create Jira issues from Github issues.
As this duplicates the working workflow in `unstructured`, it should just work.

chore: auto create jira issues

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_tesseract.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/tesseract.py

Related to [`unstructured`#458](https://github.com/Unstructured-IO/unstructured/issues/458). Adds an `ocr_languages` kwarg to enable users to call OCR with non-English language packs.
```python
layout = DocumentLayout.from_file("sample-docs/loremipsum.pdf", ocr_languages="eng+swe")
print(layout.pages[0].elements)
```

feat: add ability to pass languages to OCR agent

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py

Changed the table extraction interface. Instead of outputting the HTML table structure to the text property, the HTML structure is now stored in `html_as_text`, while the contents of `text` is the normal result of text extraction from an element.
```python
doc = DocumentLayout.from_file("sample-docs/layout-parser-paper.pdf", extract_tables=True)
tables = [el for page in doc.pages for el in page.elements if el.type == "Table"]
print(tables[0].text)
print(tables[0].text_as_html)
```

feat: move table extraction output

---

CHANGELOG.md
unstructured_inference/__version__.py

Move to release version to release the hotfix [here](https://github.com/Unstructured-IO/unstructured-inference/pull/100).

chore: move to release version

---

Makefile

Since I made the requirements files tiered, with `test.txt` solved using the pins from `base.txt`, and `dev.txt` solved using the pins from `base.txt` and `test.txt`, it follows that the there needs to be an order to the `pip-compile`s: `base.txt -> test.txt -> dev.txt`. If they are done in a different order that means `dev.txt` might end up being solved relative to an updated pin list and an old pin list, which will likely be incompatible.
Since the `Makefile` generates the compiles in the order `base -> dev -> test`, this is exactly what happened. This fix corrects the order.
Try `make pip-compile` on `main` branch, will likely fail unless the compiles are very recent.
Try `make pip-compile` on this branch. Should succeed.

fix: pip-compile test before dev

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

`PIL` records the filetype of the image when it's loaded, but the way we were handling the image destroyed the format metadata. This change keeps the image format metadata so that it can be recovered downstream.
The following code should produce output `None` on the `main` branch and output `JPEG` on this branch.
```python
doc = DocumentLayout.from_image_file("sample-docs/loremipsum.jpg")
image = doc.pages[0].image
print(image.format)
```

enhancement: preserve image format

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
setup.py
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_detectron2.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py
unstructured_inference/models/detectron2.py
unstructured_inference/models/detectron2onnx.py
unstructured_inference/models/donut.py
unstructured_inference/models/unstructuredmodel.py

Makes the ONNX version of detectron2 the default model. This means users can use it without the pain of installing detectron2. I also cleaned up a few things.
In a fresh environment, install everything without detectron with `make install-dev`, and then do the usual smoke test with:
```python
from unstructured_inference.inference.layout
doc = DocumentLayout.from_file("sample-docs/layout-parser-paper.pdf")
print(doc.pages[0].elements)
```

enhancement: make detectron2_onnx default

---

requirements/base.in

Pinning transformers at >=4.25.1. Testing on Windows just now, `pip install unstructured-inference` ended up with `transformers==4.24.x`, which caused an `ImportError` when running a smoke test due to not having a class we import. That class didn't appear until 4.25.1.
If you're up for it, on a windows machine with Python:
* Install git
* Install Visual C++ Build Tools 14.x
* Clone this repo and switch to this branch
* `pip install -e .` from the base folder of this repo
* If `pycocotools` fails to build, try `pip3 install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"` and then try to install unstructured-inference again
* Download poppler from [here](https://github.com/oschwartz10612/poppler-windows/releases)
* Unzip poppler and add the bin …

build(deps): pin transformers

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/detectron2onnx.py

This PR adds a try-catch during the inference with ONNX detectron2. 
A definitive solution would be to modify the ONNX model, however, doesn't seem like an easy change, and handling this error will allow the users to keep using the model.

fix: Exception handling for ONNX runtime on blank pages

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Page numbers weren't being correctly stored in the `PageLayout` objects. This is a fix so that page numbers are stored correctly.
```python
doc = DocumentLayout.from_file("layout-parser-paper.pdf")
print([page.number for page in doc.pages])
```
Output should be `[1, 2, 3, 4, ...]`.

fix: store page no

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/ordering.py

Temporarily short circuiting the new multi-column ordering logic after seeing examples of it misordering elements where it wasn't before.
I added a test to verify that a problem layout is ordered correctly, so with line 56 in `ordering.py` commented out, the test `test_layout_order` in `test_layout` should fail, and otherwise it should succeed.

fix: temporarily disable multicolumn logic

---

scripts/docker-build.sh
scripts/shellcheck.sh
scripts/version-sync.sh

Update all bash scripts with #!/bin/bash to use /usr/bin/env bash.

chore: update all bash scripts to use shebang: /usr/bin/env bash

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/ordering.py

Updated ordering method to rely on upper-left x-coordinate in case of a y-coordinate tie.

fix: deterministic ordering

---

CHANGELOG.md
test_unstructured_inference/models/test_chippermodel.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py
unstructured_inference/models/chipper.py

To make the new large model more customer centric, renaming it to chipper and setting a new release as this is a breaking change.

rename large model to chipper

---

requirements/base.txt
requirements/dev.txt
requirements/test.txt

This PR just makes pip-compile to requirements in -dev version.
With the current code is not possible to install unstructured along side unstructured-inference, `make install` on the last one return: 
`ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0`
In order to check:
* git clone unstructured && cd unstructured
* make install
* git clone unstructured-inference && cd unstructured-inference
* make install  
Should install without issues.

fix installation with python 3.8.17

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Exposed pdf-to-image conversion dpi parameter to higher level functions so this parameter can be set externally.
```
doc = DocumentLayout.from_file("sample-docs/loremipsum.pdf", pdf_image_dpi=200)
print(doc.pages[0].image.height) # Should be 2200
doc = DocumentLayout.from_file("sample-docs/loremipsum.pdf", pdf_image_dpi=100)
print(doc.pages[0].image.height) # Should be 1100
```

enhancement: expose dpi

---

CHANGELOG.md
Makefile
README.md
unstructured_inference/__version__.py

I noticed an issue that basic operations in this library were causing import errors. This turned out to be caused by the new version of `PIL` completing deprecation of certain references (specifically `PIL.Image.LINEAR`) used in the pinned version of `detectron2` that we've been using. Updating to the latest commit of `detectron2` fixes the problem.
From a fresh environment, run `make install` from the `main` branch and observe that running `from unstructured_inference.inference.layout import DocumentLayout` causes an import error from within the `detectron2` code.
Subsequently, if you `pip uninstall detectron2`, switch to this branch, run `make install-detectron2`, and rerun the code, it should succeed.

build(deps): update detectron2

---

README.md

In the section 'Using a non-default model', the argument name passed to DocumentLayout.from_file() must be 'detection_model' instead of 'model'

docs: Update README.md- In 'Using a non-default model', argument name updated to 'detection_model'

---

Makefile
README.md

This PR updates detectron2 (non-onnx) for using the latest version of the repository since a breaking change was done in Pillow library.
https://github.com/facebookresearch/detectron2/issues/5010

Updated detectron2 repo

---

CHANGELOG.md
test_unstructured_inference/models/test_detectron2.py
test_unstructured_inference/models/test_detectron2onnx.py
test_unstructured_inference/models/test_model.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py

Fixes the memory issue that was discovered in #152.
* Caches named models as they are loaded to prevent reloading or creating multiple copies.
* Adds test that fails if model is initialized more than once (fails on `main`).
This should also address concerns that Chipper was being loaded multiple times @ajjimeno.
The following code should run without crashing or the memory footprint exploding (takes a long time):
```python
DocumentLayout.from_file("sample-docs/pdf2image-memory-error-test-400p.pdf")
```

enhancement: cache named models

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/base.py

For reasons not yet entirely clear, using the model introduced in:
https://github.com/Unstructured-IO/unstructured-inference/commit/04b2e6fe5bf9506551714f11ffdbd1abfc28ea13
is causing regressions with how elements are labeled (esp. a lot of `UncategorizedText` vs. `NarrativeText`).
Until that is resolved, keep the old model as the default base model (but this may be overridden, as usual).

build: revert default model, cut release

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/models/tesseract.py

Certain regions of a document are failing ocr with this error:
`pytesseract.pytesseract.TesseractError: (-8, 'Estimating resolution as 1250')` (for some value)
When I try the same region on the CLI, I get:
```
$ tesseract bad_tile.jpeg output
Estimating resolution as 1813
Floating point exception
```
Whatever the root cause, let's catch this error and return an empty string.

fix: handle errors from Tesseract

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_model.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Chipper is best used when images are rendered at 300 dpi or above. This PR adds a warning if Chipper is used with DPI less than 300.
Run the following code:
```python
from unstructured_inference.inference.layout import process_file_with_model
process_file_with_model(filename="sample-docs/loremipsum.pdf", model_name="chipper", pdf_image_dpi=299)
```
You should get 2 warnings, the first being that Chipper should be used with DPI >= 300.

enhancement: warn if low dpi chipper

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Made `pdf_image_dpi` default `None` to allow for more complex handling upstream.

fix: make DPI optional with default None

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

When a pdf page doesn't have much data, it may get buffered in the write to a tempfile. If this happens, we'll hit an error reading the file back. Open to suggestions for a way to unit test this - I was creating some test files with pypdf but I couldn't trigger the error.
Steps to verify:
[bad_page.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/12363180/bad_page.pdf)
* With the attached file, run this snippet on main and confirm that there's an exception - `PDFSyntaxError: No /Root object! - Is this really a PDF?`
* Run it on this branch and confirm the error goes away
```
from unstructured_inference.inference.layout import process_data_with_model
filename = "bad_page.pdf"
with open(filename, 'rb') as f:
process_data_with_model(f, model_name="detectron2_lp")
```

fix: Fix pdfminer error when using process_data_with_model

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py

When merging extracted elements with inferred elements, extracted elements have a certain priority because they tend to have the exact text and bounding boxes. However this is not true when the extracted element is an image. In this case the element provides no insight into where in the region the text might be (if there is text in the image) and what the text is.
This is particularly bad when the pdf contains a single full-page embedded image.
This PR fixes that by skipping the embedded images during merging.
Note that the unintended behavior did provide one benefit in certain cases -- when a document contains elements with embedded images that contain text, and the detection model is unable to find the text (Examples are some scanned documents or …

fix: skip extracted images during element merge

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_donut.py
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/visualize.py

Modify `from_image_file` from class `DocumentLayout` to support reading multipage TIFF. 
Note:
The function extracts 2 pages TIFF at 1.24 ms, while extracting 2 jpgs and pngs at 1.54 and 1.32 ms respectively.

Klaijan/add tiff image file support case in from_image_file function

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

**Summary**
- Replaces using a created directory for storing image outputs with a temporary directory
- Deprecates `create_image_output_dir` method
- Adds hot-loading for annotating images because images are no longer stored long-term in a directory
- Adds a document_filename keyword arg to the PageLayout to enable hot-loading
**Tests**
Removes tests associated with `create_image_output_dir`

fix: use temporary instead of fixed directories for storing images of pdfs being processed

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/tesseract.py

I've spent some time playing with this var, and I came up with [this gist](https://gist.github.com/awalker4/8581d76d373c1bc51e0f2676a6ad816c). I ran this on a 4 core EC2 instance. Processing 3 pages without the limit takes 153s. With the limit is 5s 😍 . When the number of pages is higher than number of cores, it just hangs without this var.

fix: Set OMP_THREAD_LIMIT for better tesseract performance

---

.github/workflows/ci.yml
CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py

This PR changes some thresholds for getting the ingest test correct at `unstructured`.

Fix for wrong type assignation at ingest-test

---

CHANGELOG.md
test_unstructured_inference/test_math.py
test_unstructured_inference/test_utils.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/math.py

This PR resolves #192 by adding a helper function to perform division `a/b` and replace `b` with machine precision for float when `b==0` to avoid division by 0. 
Do we want to also have the division be type conscious (do not auto convert integers into float, i.e., if int/int we should expect int as output?)

add protection to division by 0

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_tables.py
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layout.py
unstructured_inference/models/paddle_ocr.py
unstructured_inference/models/tables.py

We need a way to use paddle for the entire page OCR since the OCR result could be better than tesseract, which has shown on some image files with tables. This PR adds an environment variable `ENTIRE_PAGE_OCR` that can be set to `paddle` or `tesseract`. We still use tesseract as default since paddle performs poorly on entire-page English PDF files.
if you are on x86 arch, please run this snippet to install paddle (paddle still doesn't work on m1/m2 chip locally):
```
pip install paddlepaddle #or pip install unstructured.paddlepaddle if on aarch64 arch
pip install unstructured_paddleocr
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
```
run the following script to see different entire page result from paddle and tesseract
```
from unstructured_inference.inference.layout import …
```

Chore: add env `ENTIRE_PAGE_OCR` to specify paddle/tesseract for entire page ocr

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_tables.py
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py

Paddle still hanging on mac so unittests related to it will fail/hang, skip those tests for local `make test`
* Added `@pytest.mark.skipif(skip_outside_ci)` check for any test that use paddle
Run `make test` on m1 chip and test will pass (tho coverage will drop from 95% to 93%)

chore: skip paddle unittests local for mac

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/config.py
unstructured_inference/models/tables.py

- refactor `tables.py` so that the structure element confidence threshold values are loaded from `inference_config`
- refactor intersection over box area threshold in `objects_to_structure` to config intead of using hardwired value of 0.5 (default is still 0.5)

feat: make table transformer parameters configurable

---

CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

- fix a bug where after padding for table transformer the detected table structure bounding boxes were not scaled or shifted correctly
- this bug can cause mis-alignment of table structure and OCR contents if padding is used
- this changeset also adds a (unit-ish) test to ensure padding is processed correctly in table transformer

fix: padded boxes are not rescaled/shifted correctly

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

- sort elements extracted by `pdfminer` to get consistent results from `aggregate_by_block()`
PDF: [recalibrating-risk-report_4-4.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/12835342/recalibrating-risk-report_4-4.pdf)
```
f_path = "dist/docs/recalibrating-risk-report_4-4.pdf"
layout = process_file_with_model(
filename=f_path,
model_name=None,
)
elements = layout.pages[0].elements
print("\n\n".join([str(el) for el in elements]))
print(len(elements))
```

Fix: sort elements extracted by `pdfminer`

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py

Currently, the `unstructured-inference` library removes control characters only from text filled by [aggregate_by_block()](https://github.com/Unstructured-IO/unstructured-inference/blob/ffb1f0b/unstructured_inference/inference/elements.py#L256). This PR is intended to remove control characters from the text of all layout elements to get clearer text. 
This PR also fixes an issue of words being concatenated together when there are spaces (e.g. `features Data` vs. `featuresData`) produced after performing OCR refactoring (attached image).
- remove control characters from text in all layout elements
- update `remove_control_characters()` to replace a newline character with a space
PDF: [main.PMC6312790_2-2.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/12851045/main.PMC6 …

enhancement: remove control characters from text in all layout elements

---

CHANGELOG.md
test_unstructured_inference/models/test_chippermodel.py
unstructured_inference/__version__.py
unstructured_inference/constants.py
unstructured_inference/models/chipper.py

Update model names so that `"chipper"` points to latest version of Chipper, while `"chipperv1"` points to old version.

chore: chipper model name should point to latest chipper version

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/chipper.py

Issue:
In some cases, PDFMiner identifies an image document as a full page and in other installations not. It is difficult to find out when PDFMiner behaves in one way or another. In either case tested, the version is `pdfminer.six v20221105`. The solution is to ignore any annotation coming from Chipper in case the full page clearing code is activated. Not sure if this is relevant to other models.

Fix PDFMiner bug

---

CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

- fix a bug where zoom factor <= 0 raises an exception at runtime
- now zoom factor <=0 will result in no scaling of the image
Related report from user: https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1697456659162509
Test:
This PR adds a unit test with cases where zoom factor is 0 or -1. Without this fix the same error the user reported shows up:
```
error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
```

fix: invalid zoom lead to cv2 error

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/chipper.py

This PR intends to solve the following issues:
* Memory leak in DonutProcessor when using large images in numpy format
* Use the right settings for beam search size > 1
* Solve a bug that in very rare cases made the last element predicted by Chipper to have a bbox = None

fix: memory leak on chipper processor, beam search parameters, and bbox bug

---

CHANGELOG.md
requirements/base.in
requirements/base.txt
requirements/sg.txt
unstructured_inference/__version__.py

`onnx` is required as an explicit dep for unstructured-inference -- it's not pulled in by `onnxruntime`.
As discovered when bumping to unstructured-inference==0.7.5 in [this unstructured commit](https://github.com/Unstructured-IO/unstructured/pull/1756/commits/1878da0f0d1c83c9f2c9efee2de6ae7d0cf437f5).

fix(deps): add onnx as base requirement

---

CHANGELOG.md
test_unstructured_inference/test_visualization.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py
unstructured_inference/visualize.py

Currently the code for annotate() don't add details when add_details=True, for example:
```
from unstructured_inference.models.base import get_model
file = "example-docs/layout-parser-paper-fast.pdf"
model = get_model("yolox_quantized")
doc = DocumentLayout.from_file(file,model)
for i,page in enumerate(doc.pages):
page.annotate(add_details=True).save(f"{i}.png")
```
After this PR is merged, the resulting image should show origin for all elements using the same code.

fix: annotate image is fixed after refactor

---

CHANGELOG.md
test_unstructured_inference/conftest.py
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

This PR addresses [CORE-2307](https://unstructured-ai.atlassian.net/browse/CORE-2307)
- add a new kwarg to `UnstructuredTableTransformerModel.run_prediction`: `output_format`
- default `output_format` is `html`, which is current behavior: output html string representation of the table
- another options available is `dataframe`, which returns a pandas dataframe representation of the table
- if not specified or any other string value for `output_format` it returns a list of dictionaries: table cell format, the original output format from table transformer
- `unstructured.model.tables.recognize` no longer accepts `out_html` kwarg and it now only returns table cell format
[CORE-2307]: https://unstructured-ai.atlassian.net/browse/CORE-2307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Feat: add more output format for table inference

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Improves kwarg handling so that kwargs are handled explicitly when needed, and suppressed otherwise.
CI should pass.

chore: streamline kwarg handling

---

.github/workflows/ci.yml

The make targets from `unstructured` used to install extras are no longer functional (need to be updated or removed). This PR updates `unstructured-inference` CI to use a working make target from `unstructured`.
Ingest test CI should succeed.

build: update ingest installation invocation

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

Removed the reference to Poppler in error message when number of images extracted doesn't match the number of page layouts extracted (I'm no longer confident that this is caused by Poppler not being installed). Also provided some details in the message about how many of each were extracted, and updated the test associated with this error.
Updated CI test should pass.

enhancement: better error message on image/page extraction mismatch

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/base.py
unstructured_inference/models/tables.py

chore: rolling slack invite link in chipper logger info

---

CHANGELOG.md
test_unstructured_inference/models/test_model.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py

Remove the logger info that user won't be able to see since chipper is only available in host API.

chore: remove logger info for chipper since its private

---

CHANGELOG.md
test_unstructured_inference/models/test_chippermodel.py
test_unstructured_inference/test_utils.py
unstructured_inference/__version__.py
unstructured_inference/models/chipper.py
unstructured_inference/utils.py

This PR addresses [CORE-2485](https://unstructured-ai.atlassian.net/browse/CORE-2485)
- now table's html representation is in `text_as_html` attribute
- the attribute `text` now only contains text without any html tags
- add a new utils to strip tags from html strings
[CORE-2485]: https://unstructured-ai.atlassian.net/browse/CORE-2485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: reformat chipper table element to match standard format

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/base.py

The `yolox` model appears to perform better on tables.

chore: change the default model to yolox

---

Makefile

This PR brings `ruff` params in line with `unstructured`.

enhancement: bring ruff params in line with unstructured

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

`"Loading the table structure model ..."` wasn't showing up in log since it was using `logging.info` not `logger.info`

Chore: nit of table init logger to show up the log info

---

.gitignore
CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/constants.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/detectron2.py
unstructured_inference/models/unstructuredmodel.py
unstructured_inference/models/yolox.py

Closes #285.
- support extracting elements with types `Picture` and `Figure`
- add a class `ElementType` for the element type constants and use the constants to replace element type strings
PDF: [algebra-graph-level1-1.pdf](https://github.com/Unstructured-IO/unstructured-inference/files/13368976/algebra-graph-level1-1.pdf)
```
doc = DocumentLayout.from_file(
filename="algebra-graph-level1-1.pdf",
extract_images_in_pdf=True,
)
```

Feat: improve image extraction by supporting all types of image elements detected by detection models

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_model.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py
unstructured_inference/models/chipper.py
unstructured_inference/models/detectron2onnx.py

Added a method to externally inject a supergradients ONNX model. By setting the environment variable `UNSTRUCTURED_DEFAULT_MODEL_NAME` one can override the default model. By setting the environment variable `UNSTRUCTURED_DEFAULT_MODEL_INITIALIZE_PARAMS_JSON_PATH`, one can specify the path to a JSON containing model initialization parameters.
```python
import os
from unstructured_inference.models.base import get_model
os.environ["UNSTRUCTURED_DEFAULT_MODEL_NAME"] = "detectron2_onnx"
model = get_model()
print(type(model))
```
Output should be `UnstructuredDetectronONNXModel` as opposed to `UnstructuredYoloXModel`.
```python
from unittest import mock
import os
import json
from unstructured_inference.models.base import get_model
from huggingface_hub import hf_hub_download
label_map = {0: …
```

enhancement: get model name and initialization params externally

---

README.md

mispelled:
paddepaddle -> paddlepaddle

Fix typo in instructions README.md

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

This PR resolves #310 
- chipper, or any page layout extracted with an element extraction model do not have key attributes like `image_metadata` populated
- this leads to `None` values for image width and height, which lead to the bug
- this fix prevents the function early return after chipper finds the elements
- it continues the logic to allow other key attributes of the page to be filled
- a bonus from this fix is we remove the image data from the page (which is not needed downstream) for chipper generated pages
A unit test is modified to test all the routes, including using an element extraction model, for page layout
Additionally grab this attached pdf and when running partition using chipper the main branch would lead to type error but this fix would run without error. …

fix: typeerror when using chipper

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py

This PR fixes #310 that is popping up again 
- now returns None instead of raising an exception
- a followup is needed to understand why some `Rectangles` has `None` value as coordinates.

fix: intersections involving rectangles with None

---

.github/workflows/ci.yml
CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

Closes #306. Addresses the condition where `recognize` returns an empty list in the `run_prediction` method on `UnstructuredTableTransformerModel`.
`pytest test_unstructured_inference/models/test_tables.py`

fix: handling for empty table recognition

---

CHANGELOG.md
Makefile
unstructured_inference/__version__.py

Removes the `install-detectron2` target from the `Makefile` since we use the ONNX version of the Detectron2 modle now.

chore: remove install-detectron2 make target

---

scripts/version-sync.sh

Fix SC2324 shellcheck warning by adding -i to indicate var type of integer and tidy up the formatting.

fix: SC2324 shellcheck

---

CHANGELOG.md
test_unstructured_inference/models/test_model.py
unstructured_inference/models/base.py

When reading the json file via `UNSTRUCTURED_DEFAULT_MODEL_INITIALIZE_PARAMS_JSON_PATH` environment variable, the label_map keys have to be converted to `int` type before it can be referenced. Added code to always convert label_map keys to `int` type.

Fix: wrong label map key type

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/config.py
unstructured_inference/inference/elements.py

This PR is the first part of fixing "embedded text not getting merged with inferred elements" and works together with the unstructured PR - https://github.com/Unstructured-IO/unstructured/pull/2679.
- replace `Rectangle.is_in()` with `Rectangle.is_almost_subregion_of()` when filling in an inferred element with embedded text
- add env_config `EMBEDDED_TEXT_AGGREGATION_SUBREGION_THRESHOLD`
The ingest test won't pass until we merge the unstructured PR - https://github.com/Unstructured-IO/unstructured/pull/2679.

Fix: embedded text not getting merged with inferred elements

---

CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

The post processing in table-transformer allows for returning multiple cells with same indexes. It happens when 1 cell is covered in more than 50% by two different spanning cells. This happens because this 'cell' is later assigned as subcell for both spanning cells instead of one with the highest probability.
Example:
Simple 2x2 table
```
```
With spanning cells over cells 'one three' (column spanning cell) and another one over 'one two' (row spanning cell). In this case cell "one" will be assigned to both spanning cells. Reproduction:
```python3
from pprint import pprint
from unstructured_inference.models.tables import structure_to_cells
table_structure = {
"rows": [
{"bbox": [0, 0, 10, 20]},
{"bbox": [10, 0, 20, 20]},
],
"columns": [
{"bbox": [0, 0, 20, 10]},
{"bbox": [0, 10, 20, 20]}, …
```

Fix cells with duplicated indexes

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/models/tables.py

This PR removes all `cid` related code. This PR is the first part of moving `cid` related code from `unstructured-inference` to `unstructured` and works together with https://github.com/Unstructured-IO/unstructured/pull/2970.

refactor: remove all `cid` related code

---

CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

Currently unstructured-inference generates tables with missing markup:
```html
<table>
<thead> 
<th>header cell1</th>
<th>header cell2</th>
</thead>
<tr> 
<td>body cell1</td>
<td>body cell2</td>
<tr>
<table>
```
When it should look like:
```html
<table>
<thead>
<tr>
<th>header cell1</th>
<th>header cell2</th>
</tr>
</thead>
<tbody>
<tr>
<td>body cell1</td>
<td>body cell2</td>
<tr>
</tbody>
<table>
```
Additionally, fixed `fill_cells` function which added redundant cells that break the HTML table layout when spanned cells were found.

fix: table HTML generation corrected

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/tables.py

This PR will address https://github.com/Unstructured-IO/unstructured-inference/issues/357 and https://github.com/Unstructured-IO/unstructured-inference/issues/358.
- add logic to validate the input parameter to the fill_cells() function. Now, the function checks if the input is a list of dictionaries before processing.
- correct type hint for parameter `cells` in `table_cells_to_dataframe()`

fix: ValueError when converting cells to html

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

**Summary**
Remove use of `tempfile.NamedTemporaryFile` which attempts to access the temporary file by name. This fails on Windows. Use `tempfile.TemporaryDirectory` instead.
Fixes #303

fix(layout): Windows support

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
test_unstructured_inference/inference/test_layout.py
test_unstructured_inference/models/test_model.py
test_unstructured_inference/models/test_yolox.py
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layout.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/base.py
unstructured_inference/models/unstructuredmodel.py
unstructured_inference/models/yolox.py

This PR adds two new vectorized page level dataclasses:
- `TextRegions`: replaces a `list[TextRegion]` and store coordinates and texts as numpy arrays for more efficient memory operations when the number of items is large
- `LayoutElements`: replaces a `list[LayoutElement]` and store data in numpy arrays as above
In addition this PR refactors `yolox` model inference to use those two new classes above internally while keeping the list data structure still available for backward compatibility (e.g., passing into a `PageLayout` object). 
compare memory usage and runtime on a pdf image using
```python
from unstructured_inference.inference.layout import process_file_with_model
def main():
f = "/Users/yaoyou/Downloads/002489.pdf"
layout = process_file_with_model(f, model_name="yolox") …
```

vectorize layout elements

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py

Importing `TextRegion` from `unstructured_inference.inference.elements` causes the following error
```
File "<stdin>", line 1, in <module>
File "/home/filip/Unstructured/unstructured-inference/unstructured_inference/inference/elements.py", line 209, in <module>
@dataclass
^^^^^^^^^
File "/home/filip/.pyenv/versions/3.12.1/lib/python3.12/dataclasses.py", line 1266, in dataclass
return wrap(cls)
^^^^^^^^^
File "/home/filip/.pyenv/versions/3.12.1/lib/python3.12/dataclasses.py", line 1256, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/filip/.pyenv/versions/3.12.1/lib/python3.12/dataclasses.py", line 994, in _process_class
cls_fields.append(_get_field(cls, name, type, kw_only)) …
```

fix: invalid dataclass mutable default

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py

Fix an issue where numpy array is used as default value to dataclass attribute. Similar to https://github.com/Unstructured-IO/unstructured-inference/pull/388 but for the LayoutElements class

use field to set default empty array

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layoutelement.py
unstructured_inference/models/yolox.py

This PR fixes two bugs:
- fix a type casting issue when subtracting a int array with a float. This popped up when testing with `unstructured`, and some sources of element coordinates are of `int` type. This PR adds a new unit test case for `int` coord type with the grouping function
- fix element class id 0 becomes None bug: this happens when dumping `LayoutElements` as a list of `LayoutElement`. When an element class id is 0 the logic on main would treat it as no existing and use `None` as the type.

fix: fix bugs in layoutelements

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py

error coming from https://github.com/Unstructured-IO/core-product/actions/runs/11510770484/job/32043653203?pr=662#step:5:718
or lmk if there are better way to fix error w/o changing here :)

fix: list index out of range error caused by calling LayoutElements.from_list() with empty list

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layoutelement.py

- fix bug when an empty list is passed into `TextRegions.from_list`
- fix bug when concatenating a list of `LayoutElements` the class id maps is not updated correctly

fix: fix bugs in data structure

---

CHANGELOG.md
README.md
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt
test_unstructured_inference/inference/test_layout_element.py
unstructured_inference/__version__.py
unstructured_inference/inference/layoutelement.py

this PR is to remove the layoutparser lib as we no longer rely on it anymore
hence the README.md is also updated to drop the note on supporting layoutparser model zoo

remove layoutparser lib

---

CHANGELOG.md
requirements/base.in
requirements/base.txt
requirements/dev.txt
unstructured_inference/__version__.py

when removing layoutparser package, there are some packages that installed as a dependency by layoutparser also removed.
This PR is to bring back the necessary packages still required by other scripts to pass CI. Previously, included pdfplumber to cover those deps. however, pdfminer version is bounded by pdfplumber in `unstructured`. so instead, explicitly bump the pdfminer version here

include pdfminer in base.in

---

CHANGELOG.md
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/inference/elements.py
unstructured_inference/inference/layoutelement.py

This PR adds `source` back to `TextRegions` and `LayoutElements` for backward compatibility.

feat: add back source attribute for backward compatibility

---

CHANGELOG.md
test_unstructured_inference/inference/test_layout.py
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

- default `PageLayout.get_elements_with_detection_model` now returns `LayoutElements`
- `PageLayout.elements` is a cached property computed from `elements_array` property to save memory and cpu costs

feat: make PageLayout.elements a cached property

---

CHANGELOG.md
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt
unstructured_inference/__version__.py

- higher versions can have bugs that user have reported
- unpin it in the base.in so leaves other packages and user's constrains to resolve it

unpin pdfminer-six

---

CHANGELOG.md
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt
test_unstructured_inference/test_elements.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py

This PR allows the library to be compatible with `numpy>=2`.

unpin numpy and raise min for onnx higher to be compatible

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/models/tables.py

Prevent it from giving an exception with newer models.
https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-all/discussions/1

Adding preprocessor parameters

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/config.py
unstructured_inference/models/tables.py

This PR parametrizes the edge config for `DetrImageProcessor` model used for table transformer.

parametrize edge config

---

CHANGELOG.md
test_unstructured_inference/models/test_tables.py
unstructured_inference/__version__.py
unstructured_inference/models/base.py
unstructured_inference/models/tables.py

This PR puts table model initialization behind a threadlock so it is thread safe. 
Use the following script to test (after changing extension) loading model in multithreading env.
[test_threading.txt](https://github.com/user-attachments/files/20560179/test_threading.txt)

feat: use thread lock to prevent racing condition

---

CHANGELOG.md
unstructured_inference/__version__.py
unstructured_inference/inference/layout.py

This is a minor fix to improve our logging. When we buffer a file like input to disk in `process_data_with_model`, we always use the name `document.pdf`. This confused me when I found this in our logs:
```
2025-06-30 17:02:01,906 unstructured_inference INFO Reading image file: /var/folders/5k/frv076q97yl0ywybmzydhbsr0000gn/T/tmpc0uq7zde/document.pdf ...
2025-06-30 17:02:01,951 unstructured_api ERROR cannot identify image file '/private/var/folders/5k/frv076q97yl0ywybmzydhbsr0000gn/T/tmpc0uq7zde/document.pdf'
```
This path can be either pdfs or images, so let's just drop the extension to save ourselves some confusion.
Also added a comment so we don't forget why it's using a temp dir, not a temp file.

fix: Do not hardcode file extension on temp files
