- requirements/base.txt
- requirements/dev.txt
- requirements/test.in
- requirements/test.txt
Update dependencies through `pip-compile`.
> chore: update deps

- Makefile
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
> build(deps): bump dependency versions

- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- unstructured_inference/__version__.py
Update `detectron2` version to be consistent across repos.
CI should pass.
> build: update detectron2 version

- test_unstructured_inference/inference/test_layout.py
- test_unstructured_inference/models/test_detectron2.py
- test_unstructured_inference/models/test_model.py
- unstructured_inference/models/detectron2.py
- Fixed interpretation of outputs, for example detectron bbox format is `(x1, y1, x2, y2)` instead of `(x1, y1, w, h)`
- Converted bbox coordinates to agree with original image dimensions
- Some (IMO) readability improvements
- Split `image_processing` function into pre and post processing, driven from the `predict` function
- Test updates (should all be passing right now)
- Type checking is passing
Have a look and see if you agree with the changes @benjats07 .
> Misc updates and tests

- CHANGELOG.md
- unstructured_inference/__version__.py
> chore: bump for release

- .github/workflows/ci.yml
Update connector installs to keep current with `unstructured` library.
> build: update connector installs

- CHANGELOG.md
- test_unstructured_inference/models/test_model.py
- unstructured_inference/__version__.py
- unstructured_inference/models/base.py
Adds a warning indicating that Chipper is still in beta.
> chore: beta warning for chipper

- CHANGELOG.md
- unstructured_inference/__version__.py
Unstructed library needs to leverage some of the new features that have been added since the 0.5.5 release. Cutting a new one to expose that and publish it.
> Cut 0.5.6 release

- CHANGELOG.md
- Makefile
- requirements/base.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/test.txt
- unstructured_inference/__version__.py
Update pip version to latest (23.2.1)
Test: `make install` has no pip warnings
> Update pip in makefile

- .github/workflows/ci.yml
- scripts/test-unstructured-ingest-helper.sh
so more diff's may be inspected.
> build: don't exit after first ingest test failure

- .pre-commit-config.yaml
- add config yaml (copied from `unstructured` repo)
- helps with dev's Quality of Life
> feat: add pre commit hook

- CHANGELOG.md
- test_unstructured_inference/models/test_chippermodel.py
- unstructured_inference/__version__.py
- unstructured_inference/models/chipper.py
Reverts Unstructured-IO/unstructured-inference#295
> Revert "Feat/chipper repetitions"

- CHANGELOG.md
- unstructured_inference/__version__.py
- unstructured_inference/constants.py
This PR adds some new element types that can be used especially by pdf/image parition.
The new element types correspond to the ones added in unstructured in this PR:
https://github.com/Unstructured-IO/unstructured/pull/2700
> feat: add new element types

- CHANGELOG.md
- unstructured_inference/__version__.py
- unstructured_inference/inference/layout.py
- unstructured_inference/models/tables.py
This PR removes some info level logging that doesn't provide actionable information.
> chore: reduce excessive logging

- .github/workflows/ci.yml
Updated setup-python github action version.
> build(deps): update setup-python gha

- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
It looks like there have been a number of upstream updates, so I want to get those pulled in.
> build(deps): Update requirements

- .github/workflows/ci.yml
Maintenance PR to update github action versions.
> build: update github action versions

- CHANGELOG.md
- unstructured_inference/__version__.py
> update version and changelog for release

- CHANGELOG.md
- unstructured_inference/__version__.py
- unstructured_inference/models/yolox.py
This PR fixes the data type for probabilities from int to float.
> fix: fix probability data type

- CHANGELOG.md
- unstructured_inference/__version__.py
- unstructured_inference/models/base.py
- unstructured_inference/models/tables.py
- where previously global was used now they are singleton class variables
- this avoids issues with multi-threading env
> feat: use singleton instead of global
